### PR TITLE
BACK-2469: Remove hard documentation from readme. Refactor remaining information

### PR DESCRIPTION
**Pull request by sjl2024**
This branch simplifies the Flex SDK readme and links to all relevant/removed information (similar to the lodash README: https://github.com/lodash/lodash)

It's probably easier to view the raw file or checkout the branch and open it in a markdown editor in order to visualize the differences (the diff is quite large)

### CODE REVIEW

**Comment by andrewmaillet** [comment]
The FlexAuth example references flexFunctions.register(...).  Is that correct?

**Comment by andrewmaillet** [comment]
What do you think of moving the Initialization Options above the Sample Service examples.  Also, what happens if the port number is left in when deploying to FSR?

**Comment by sjl2024** [comment]
```The FlexAuth example references flexFunctions.register(...). Is that correct?```
You tell me :)

```Also, what happens if the port number is left in when deploying to FSR?```
This would be one for Mike, but I believe that this only applies to running locally (i.e. when using the underlying HTTPReceiver. The TCPReceiver [prod] is unaffected)

I suppose it would make more sense to move the init options to just before the examples. Will do.

@andrewmaillet

**Comment by sjl2024** [comment]
Adding @ivanstoyanov as well, who may have some thoughts.

**Comment by sjl2024** [comment]
Feedback pushed @ivanstoyanov @andrewmaillet

**Pull request merged**
