### PR TITLE
Add groupStore module

### PR DESCRIPTION
**Pull request by wongni**
I suggest to add groupStore along with userStore and dataStore, which invokes REST API calls described in http://devcenter.kinvey.com/rest/guides/users#usergroups. I referred userStore and its unit test code mainly.

### CODE REVIEW

**Comment by mjsalinger** [comment]
Hi @wongni, 

Thanks for the PR!  We just completed a slight refactor of our user/group stores that put common code in a baseStore.  The changes aren't released yet but they are in master.  Can you rebase your Pull Request and refactor the new groupStore to bring it in line with the new architecture?

Thanks!

**Comment by wongni** [comment]
Hi Michael,

I am pretty new to github so can you list the commands I should enter to
rebase my pull request?

**Comment by sjl2024** [comment]
@wongni sure!

1. Check out the master branch and ensure it's up-to-date: `git checkout master && git pull`
2. Check out the target branch: `wongni:feature/add-groupStore-module`
3. Lastly, initiate the rebase process with the following: `git rebase master`

Some [helpful information about rebasing](https://git-scm.com/book/en/v2/Git-Branching-Rebasing)

Also, check out the new [BaseStore](https://github.com/Kinvey/flex-sdk/blob/master/lib/service/modules/baseStore.js) and [UserStore](https://github.com/Kinvey/flex-sdk/blob/master/lib/service/modules/baseStore.js) if you haven't seen the changes yet.

Let us know if you have any other questions!

**Comment by wongni** [comment]
I applied the refactoring done for baseStore and userStore to groupStore. Please review it.

**Comment by mjsalinger** [comment]
Hi @wongni,

Something seems to have gone wrong with the rebase...  I'd suggest we start over and try again..

1) Go to your master branch, and do a git pull from upstream.  (If you have upstream set as one of your remotes). 
2) Create a new branch (git checkout -b <branch name>)
3) Add your two commits only:  
```git cherry-pick 9b6f016``` and ``git cherry-pick fc4dfd5```
4) Push up the new branch, and create a new PR.

Let's see if that works.

Thanks!

**Comment by wongni** [comment]
Hi Michael,

I followed the procedure and created a new PR here!
https://github.com/Kinvey/flex-sdk/pull/43
It looks a lot cleaner. Thanks for the help!

Best regards,
Wonkun

On Mon, Feb 20, 2017 at 12:48 PM, Michael Salinger <notifications@github.com

**Pull request closed without merging**
